# Generated by Django 3.1.7 on 2021-02-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
        ("accounts", "0002_auto_20210227_1337"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorites",
            field=models.ManyToManyField(to="recipes.Recipe"),
        ),
    ]
