# Generated by Django 3.1.7 on 2021-02-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorites',
            new_name='favorite_recipes',
        ),
    ]
