# Generated by Django 3.1.6 on 2021-02-18 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for this recipe', max_length=200)),
                ('servings', models.IntegerField(help_text='Enter the number of servings this recipe makes')),
                ('nota_bene', models.TextField(help_text='Add any useful notes, hints or advice for this recipe', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="Add a step to the recipe's instructions")),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of an ingredient (e.g. garlic)', max_length=100)),
                ('amount', models.CharField(help_text='Enter the amount to use (e.g. 1/4 tsp.)', max_length=20)),
                ('preparation', models.CharField(help_text='Describe this ingredient"s preparation (e.g. finely minced) or leave blank', max_length=100, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
