# Generated by Django 3.1.6 on 2021-02-24 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='owner',
            new_name='author',
        ),
    ]
